name: Sanity Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Checking linting
        run: go get -u golang.org/x/lint/golint && `go list -f {{.Target}} golang.org/x/lint/golint` ./...

  test:
    name: Run All Tests
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.codecov_token }}
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test with coverage
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to codecov
      run: bash <(curl -s https://codecov.io/bash)
